version: '3'
services:
  app:
    build: .
    network_mode: "host"
    ports:
      - "12345:12345/udp"
      - "3000:3000"  # Nuxt.js default port
      - "5000:5000"  # Flask default port
    environment:
      - NUXT_HOST=0.0.0.0
      - NUXT_PORT=3000
