// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x050056), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Screen1, lv_color_hex(0x000238), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Screen1, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_Screen1);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 130);
    lv_obj_set_y(ui_Label1, 0);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Hello Fabian");
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Checkbox1 = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_Checkbox1, "Node 1");
    lv_obj_set_width(ui_Checkbox1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox1, -152);
    lv_obj_set_y(ui_Checkbox1, 120);
    lv_obj_set_align(ui_Checkbox1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox2 = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_Checkbox2, "Node 2");
    lv_obj_set_width(ui_Checkbox2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox2, 0);
    lv_obj_set_y(ui_Checkbox2, 120);
    lv_obj_set_align(ui_Checkbox2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Checkbox3 = lv_checkbox_create(ui_Screen1);
    lv_checkbox_set_text(ui_Checkbox3, "Node 3");
    lv_obj_set_width(ui_Checkbox3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Checkbox3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Checkbox3, 140);
    lv_obj_set_y(ui_Checkbox3, 120);
    lv_obj_set_align(ui_Checkbox3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Checkbox3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Button1 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button1, 100);
    lv_obj_set_height(ui_Button1, 50);
    lv_obj_set_x(ui_Button1, 0);
    lv_obj_set_y(ui_Button1, -125);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn1Label = lv_label_create(ui_Button1);
    lv_obj_set_width(ui_btn1Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btn1Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btn1Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btn1Label, "Data");

    ui_Button2 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button2, 100);
    lv_obj_set_height(ui_Button2, 50);
    lv_obj_set_x(ui_Button2, 120);
    lv_obj_set_y(ui_Button2, -125);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btn2Label = lv_label_create(ui_Button2);
    lv_obj_set_width(ui_btn2Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btn2Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btn2Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_btn2Label, "Bridge");

    ui_Button3 = lv_btn_create(ui_Screen1);
    lv_obj_set_width(ui_Button3, 100);
    lv_obj_set_height(ui_Button3, 50);
    lv_obj_set_x(ui_Button3, 240);
    lv_obj_set_y(ui_Button3, -125);
    lv_obj_set_align(ui_Button3, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button3, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bnt3Label = lv_label_create(ui_Button3);
    lv_obj_set_width(ui_bnt3Label, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_bnt3Label, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_bnt3Label, LV_ALIGN_CENTER);
    lv_label_set_text(ui_bnt3Label, "Settings");

    ui_Panel1 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel1, 300);
    lv_obj_set_height(ui_Panel1, 300);
    lv_obj_set_x(ui_Panel1, -240);
    lv_obj_set_y(ui_Panel1, -80);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_IPLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_IPLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_IPLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_IPLabel, -35);
    lv_obj_set_y(ui_IPLabel, -120);
    lv_obj_set_align(ui_IPLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_IPLabel, "IP: xxx.xxx.xxx.xxx");
    lv_obj_set_style_text_font(ui_IPLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MacLabel = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_MacLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MacLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MacLabel, -20);
    lv_obj_set_y(ui_MacLabel, -90);
    lv_obj_set_align(ui_MacLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MacLabel, "MAC: xx:xx:xx:xx:xx:xx");
    lv_obj_set_style_text_font(ui_MacLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MasterFound = lv_checkbox_create(ui_Panel1);
    lv_checkbox_set_text(ui_MasterFound, "Master Found");
    lv_obj_set_width(ui_MasterFound, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MasterFound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MasterFound, -75);
    lv_obj_set_y(ui_MasterFound, 130);
    lv_obj_set_align(ui_MasterFound, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MasterFound, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MasterFound, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    ui_Panel2 = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel2, 300);
    lv_obj_set_height(ui_Panel2, 300);
    lv_obj_set_x(ui_Panel2, -240);
    lv_obj_set_y(ui_Panel2, -80);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Panel2, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_tempLabel = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_tempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_tempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_tempLabel, -15);
    lv_obj_set_y(ui_tempLabel, -120);
    lv_obj_set_align(ui_tempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_tempLabel, "Temperature [°C]: 00");
    lv_obj_set_style_text_font(ui_tempLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_switchLabel = lv_label_create(ui_Panel2);
    lv_obj_set_width(ui_switchLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_switchLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_switchLabel, -50);
    lv_obj_set_y(ui_switchLabel, -90);
    lv_obj_set_align(ui_switchLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_switchLabel, "Switch State: x");
    lv_obj_set_style_text_font(ui_switchLabel, &lv_font_montserrat_24, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button3, ui_event_Button3, LV_EVENT_ALL, NULL);

}
